/**
 * One-page denizen stat-block PDF via pdfmake, set in the book's type stack
 * (IM Fell English body, HamletOrNot display, Caslon Antique section heads —
 * all free faces, served from /static/fonts/hmtw). IM Fell has no bold, so the
 * bold slot maps to Caslon Antique Bold, which is what ability names render in.
 *
 * `buildDenizenDocDefinition` is pure (exported for unit testing without
 * loading pdfmake); the download helper is the thin browser wrapper.
 */

import type { DenizenDefinition, DenizenAbility } from '$lib/types/content-pack';
import { abilityLabel } from '$lib/utils/ability-label';

const INK = '#241b14';
const SOFT = '#4a4034';

const DISCLAIMER =
	'His Majesty the Worm is copyright Joshua McCrowell. Guild Book is an independent production by Arrowed and is not affiliated with Joshua McCrowell or Exalted Funeral. Generated by Guild Book.';

/** Strip the content pack's markdown markers for plain PDF text. */
function plain(md: string): string {
	return md.replace(/\*\*(.+?)\*\*/g, '$1').replace(/\*(.+?)\*/g, '$1').replace(/`/g, '');
}

function sectionHeader(text: string) {
	return { text, style: 'sectionHeader' };
}

/** "Label: value" line with the label in Caslon Antique, per the book. */
function statLine(label: string, value: string) {
	return {
		text: [{ text: `${label}: `, style: 'statLabel' }, { text: value }],
		style: 'body',
		// A blank line after each stat line lets the block breathe.
		margin: [0, 2, 0, 12] as [number, number, number, number]
	};
}

function abilityList(title: string, list: DenizenAbility[] | undefined): unknown[] {
	if (!list?.length) return [];
	return [
		sectionHeader(title),
		{
			ul: list.map((a) => ({
				text: [{ text: `${abilityLabel(a.name)} `, bold: true }, { text: plain(a.text) }]
			})),
			style: 'body',
			// A blank line's worth of air after the bullets, before the next heading.
			margin: [0, 2, 0, 12] as [number, number, number, number]
		}
	];
}

/** Build a pdfmake document definition from a denizen. Pure. */
export function buildDenizenDocDefinition(
	denizen: DenizenDefinition,
	themeName: string,
	threatName: string
) {
	const attrs = denizen.attributes;

	const content: unknown[] = [
		{ text: denizen.name, style: 'title' },
		{ text: [themeName, threatName].filter(Boolean).join(' '), style: 'subtitle' },
		{ text: plain(denizen.flavor), style: 'flavor', margin: [0, 8, 0, 12] },
		statLine(
			'Attributes',
			`Swords ${attrs.swords} | Pentacles ${attrs.pentacles} | Cups ${attrs.cups} | Wands ${attrs.wands}`
		)
	];

	if (denizen.health !== undefined && denizen.defense !== undefined) {
		content.push(statLine('Health/Defense', `${denizen.health}/${denizen.defense}`));
	}
	if (denizen.statNote) {
		content.push({ text: plain(denizen.statNote), style: 'flavor', margin: [0, 0, 0, 12] });
	}
	if (denizen.likes?.length) content.push(statLine('Likes', denizen.likes.join(', ')));
	if (denizen.hates?.length) content.push(statLine('Hates', denizen.hates.join(', ')));

	if (denizen.specialRules) {
		content.push(sectionHeader('Special rules'), {
			text: plain(denizen.specialRules),
			style: 'body'
		});
	}

	content.push(
		...abilityList('Notes', denizen.notes),
		...abilityList('Lesser dooms', denizen.lesserDooms),
		...abilityList('Greater dooms', denizen.greaterDooms)
	);

	for (const pool of denizen.pools ?? []) {
		// A pool may omit its HD pair, and builder drafts can hold an incomplete
		// pair — omit HD rather than render "3/", "/", or "undefined/undefined".
		const poolHd =
			pool.health !== undefined && pool.defense !== undefined
				? `  Health/Defense: ${pool.health}/${pool.defense}` // plain-space separator: HamletOrNot has no em-dash glyph
				: '';
		content.push({
			text: `${pool.name}${poolHd}`,
			style: 'poolTitle'
		});
		if (pool.text) content.push({ text: plain(pool.text), style: 'body' });
		content.push(
			...abilityList('Notes', pool.notes),
			...abilityList('Lesser dooms', pool.lesserDooms),
			...abilityList('Greater dooms', pool.greaterDooms)
		);
	}

	for (const sidebar of denizen.sidebars ?? []) {
		content.push(sectionHeader(sidebar.title), { text: plain(sidebar.body), style: 'body' });
	}

	content.push({ text: DISCLAIMER, style: 'disclaimer', margin: [0, 20, 0, 0] });

	return {
		pageSize: 'LETTER',
		pageMargins: [40, 40, 40, 40] as [number, number, number, number],
		defaultStyle: { font: 'IMFellEnglish', fontSize: 10.5, color: INK },
		styles: {
			title: { font: 'HamletOrNot', fontSize: 24, color: INK },
			subtitle: { fontSize: 12, italics: true, color: SOFT, margin: [0, 2, 0, 0] },
			flavor: { fontSize: 10.5, italics: true, color: SOFT },
			sectionHeader: { font: 'CaslonAntique', fontSize: 16, color: INK, margin: [0, 10, 0, 3] },
			poolTitle: { font: 'HamletOrNot', fontSize: 18, color: INK, margin: [0, 14, 0, 4] },
			statLabel: { font: 'CaslonAntique', fontSize: 16 },
			body: { fontSize: 10.5, color: INK, margin: [0, 2, 0, 0] },
			disclaimer: { fontSize: 7, color: SOFT, italics: true }
		},
		content
	};
}

// --- browser rendering -------------------------------------------------------

/**
 * The four faces served from static/. IM Fell English has no bold, so bold
 * (used for ability names) maps to Caslon Antique Bold — matching the book's
 * mixed-face look. HamletOrNot and Caslon Antique only ship one style each.
 */
const FONT_SOURCES: Record<string, string> = {
	'IMFellEnglish-Regular.ttf': '/fonts/hmtw/IMFellEnglish-Regular.ttf',
	'IMFellEnglish-Italic.ttf': '/fonts/hmtw/IMFellEnglish-Italic.ttf',
	'HamletOrNot.ttf': '/fonts/hmtw/HamletOrNot.ttf',
	'CaslonAntique-Bold.ttf': '/fonts/hmtw/CaslonAntique-Bold.ttf'
};

const FONT_FAMILIES = {
	IMFellEnglish: {
		normal: 'IMFellEnglish-Regular.ttf',
		italics: 'IMFellEnglish-Italic.ttf',
		bold: 'CaslonAntique-Bold.ttf',
		bolditalics: 'CaslonAntique-Bold.ttf'
	},
	HamletOrNot: {
		normal: 'HamletOrNot.ttf',
		italics: 'HamletOrNot.ttf',
		bold: 'HamletOrNot.ttf',
		bolditalics: 'HamletOrNot.ttf'
	},
	CaslonAntique: {
		normal: 'CaslonAntique-Bold.ttf',
		italics: 'CaslonAntique-Bold.ttf',
		bold: 'CaslonAntique-Bold.ttf',
		bolditalics: 'CaslonAntique-Bold.ttf'
	}
};

function toBase64(buffer: ArrayBuffer): string {
	const bytes = new Uint8Array(buffer);
	let binary = '';
	const chunk = 0x8000; // avoid call-stack limits on large fonts
	for (let i = 0; i < bytes.length; i += chunk) {
		binary += String.fromCharCode(...bytes.subarray(i, i + chunk));
	}
	return btoa(binary);
}

let fontVfsPromise: Promise<Record<string, string>> | null = null;

function loadFontVfs(): Promise<Record<string, string>> {
	if (!fontVfsPromise) {
		fontVfsPromise = (async () => {
			const entries = await Promise.all(
				Object.entries(FONT_SOURCES).map(async ([name, url]) => {
					const response = await fetch(url);
					if (!response.ok) throw new Error(`Failed to load font ${url}: ${response.status}`);
					return [name, toBase64(await response.arrayBuffer())] as const;
				})
			);
			return Object.fromEntries(entries);
		})();
		// A transient fetch failure must not poison the cache for the rest of
		// the page session — drop the rejected promise so a retry refetches.
		fontVfsPromise.catch(() => {
			fontVfsPromise = null;
		});
	}
	return fontVfsPromise;
}

/** Trigger a browser download of the denizen stat-block PDF. */
export async function downloadDenizenPDF(
	denizen: DenizenDefinition,
	themeName: string,
	threatName: string
): Promise<void> {
	const [pdfMake, vfs] = await Promise.all([
		import('pdfmake/build/pdfmake').then((m) => m.default),
		loadFontVfs()
	]);
	pdfMake.addVirtualFileSystem(vfs);
	pdfMake.addFonts(FONT_FAMILIES);
	const filename = `${(denizen.name || 'denizen').replace(/[^a-z0-9]+/gi, '-').toLowerCase()}.pdf`;
	pdfMake.createPdf(buildDenizenDocDefinition(denizen, themeName, threatName)).download(filename);
}
