/**
 * One-page denizen stat-block PDF via pdfmake, matching the adventurer sheet's
 * look. Original layout — no His Majesty the Worm art or trade dress; matching
 * the book's typeface would require embedding licensed fonts (follow-up).
 *
 * `buildDenizenDocDefinition` is pure (exported for unit testing without
 * loading pdfmake); the download helper is the thin browser wrapper.
 */

import type { DenizenDefinition, DenizenAbility } from '$lib/types/content-pack';

const INK = '#241b14';
const SOFT = '#4a4034';
const ACCENT = '#6a1f16';
const BAND_TEXT = '#f3ead6';

const DISCLAIMER =
	'His Majesty the Worm is copyright Joshua McCrowell. Guild Book is an independent production by Arrowed and is not affiliated with Joshua McCrowell or Exalted Funeral. Generated by Guild Book.';

function band(text: string) {
	return {
		table: { widths: ['*'], body: [[{ text: text.toUpperCase(), style: 'band' }]] },
		layout: 'noBorders',
		margin: [0, 10, 0, 4] as [number, number, number, number]
	};
}

/** Strip the content pack's markdown markers for plain PDF text. */
function plain(md: string): string {
	return md.replace(/\*\*(.+?)\*\*/g, '$1').replace(/\*(.+?)\*/g, '$1').replace(/`/g, '');
}

function abilityList(title: string, list: DenizenAbility[] | undefined): unknown[] {
	if (!list?.length) return [];
	return [
		band(title),
		{ ul: list.map((a) => `${a.name}. ${plain(a.text)}`), style: 'body' }
	];
}

/** Build a pdfmake document definition from a denizen. Pure. */
export function buildDenizenDocDefinition(
	denizen: DenizenDefinition,
	themeName: string,
	threatName: string
) {
	const attrs = denizen.attributes;
	const attrCells = (
		[
			['Swords', attrs.swords],
			['Pentacles', attrs.pentacles],
			['Cups', attrs.cups],
			['Wands', attrs.wands]
		] as const
	).map(([name, value]) => ({
		stack: [
			{ text: String(value), style: 'attrValue' },
			{ text: name, style: 'attrName' }
		],
		alignment: 'center' as const
	}));

	const content: unknown[] = [
		{ text: denizen.name, style: 'title' },
		{ text: `${themeName} ${threatName}`, style: 'subtitle' },
		{ text: plain(denizen.flavor), style: 'flavor', margin: [0, 8, 0, 0] },
		{
			table: { widths: ['*', '*', '*', '*'], body: [attrCells] },
			layout: 'noBorders',
			margin: [0, 10, 0, 0]
		}
	];

	const statBits: string[] = [];
	if (denizen.health !== undefined && denizen.defense !== undefined) {
		statBits.push(`Health/Defense ${denizen.health}/${denizen.defense}`);
	}
	if (denizen.likes?.length) statBits.push(`Likes: ${denizen.likes.join(', ')}`);
	if (denizen.hates?.length) statBits.push(`Hates: ${denizen.hates.join(', ')}`);
	if (statBits.length) {
		content.push({ text: statBits.join('     '), style: 'body', margin: [0, 8, 0, 0] });
	}
	if (denizen.statNote) {
		content.push({ text: plain(denizen.statNote), style: 'flavor', margin: [0, 4, 0, 0] });
	}

	if (denizen.specialRules) {
		content.push(band('Special rules'), { text: plain(denizen.specialRules), style: 'body' });
	}

	content.push(
		...abilityList('Notes', denizen.notes),
		...abilityList('Lesser dooms', denizen.lesserDooms),
		...abilityList('Greater dooms', denizen.greaterDooms)
	);

	for (const pool of denizen.pools ?? []) {
		content.push(band(`${pool.name} — HD ${pool.health}/${pool.defense}`));
		if (pool.text) content.push({ text: plain(pool.text), style: 'body' });
		content.push(
			...abilityList('Notes', pool.notes),
			...abilityList('Lesser dooms', pool.lesserDooms),
			...abilityList('Greater dooms', pool.greaterDooms)
		);
	}

	for (const sidebar of denizen.sidebars ?? []) {
		content.push(band(sidebar.title), { text: plain(sidebar.body), style: 'body' });
	}

	content.push({ text: DISCLAIMER, style: 'disclaimer', margin: [0, 20, 0, 0] });

	return {
		pageSize: 'LETTER',
		pageMargins: [40, 40, 40, 40] as [number, number, number, number],
		defaultStyle: { fontSize: 10, color: INK },
		styles: {
			title: { fontSize: 26, bold: true, color: INK },
			subtitle: { fontSize: 12, italics: true, color: SOFT, margin: [0, 2, 0, 0] },
			flavor: { fontSize: 10, italics: true, color: SOFT },
			band: { fontSize: 10, bold: true, color: BAND_TEXT, fillColor: ACCENT, margin: [6, 3, 6, 3] },
			attrValue: { fontSize: 22, bold: true, color: INK },
			attrName: { fontSize: 9, color: SOFT },
			body: { fontSize: 10, color: INK, margin: [0, 2, 0, 0] },
			disclaimer: { fontSize: 7, color: SOFT, italics: true }
		},
		content
	};
}

async function getPdfMake() {
	const pdfMake = (await import('pdfmake/build/pdfmake')).default;
	const pdfFonts = (await import('pdfmake/build/vfs_fonts')).default;
	pdfMake.addVirtualFileSystem(pdfFonts);
	return pdfMake;
}

/** Trigger a browser download of the denizen stat-block PDF. */
export async function downloadDenizenPDF(
	denizen: DenizenDefinition,
	themeName: string,
	threatName: string
): Promise<void> {
	const pdfMake = await getPdfMake();
	const filename = `${(denizen.name || 'denizen').replace(/[^a-z0-9]+/gi, '-').toLowerCase()}.pdf`;
	await pdfMake.createPdf(buildDenizenDocDefinition(denizen, themeName, threatName)).download(filename);
}
