/**
 * One-page adventurer sheet PDF via pdfmake. Original layout — no His Majesty
 * the Worm art or trade dress. Client-side only.
 *
 * `buildDocDefinition` is pure (exported for unit testing without loading
 * pdfmake); `generatePDF` is the thin browser wrapper that renders it.
 */

import type { CharacterView } from '$lib/types/character-view';

const INK = '#241b14';
const SOFT = '#4a4034';
const ACCENT = '#6a1f16';
const BAND_TEXT = '#f3ead6';

const DISCLAIMER =
	'His Majesty the Worm is copyright Joshua McCrowell. Guild Book is an independent production by Arrowed and is not affiliated with Joshua McCrowell or Exalted Funeral. Generated by Guild Book.';

function band(text: string) {
	return {
		table: { widths: ['*'], body: [[{ text: text.toUpperCase(), style: 'band' }]] },
		layout: 'noBorders',
		margin: [0, 10, 0, 4] as [number, number, number, number]
	};
}

/** Build a pdfmake document definition from a resolved character view. Pure. */
export function buildDocDefinition(view: CharacterView) {
	const subtitle = [view.kin && view.kith ? `${view.kin} (${view.kith})` : view.kin, view.path]
		.filter(Boolean)
		.join('   ·   ');

	const attrCells = view.attributes.map((a) => ({
		stack: [
			{ text: String(a.value), style: 'attrValue' },
			{ text: a.name, style: 'attrName' }
		],
		alignment: 'center' as const
	}));

	const content: unknown[] = [
		{ text: view.name || 'Unnamed Adventurer', style: 'title' },
		subtitle ? { text: subtitle, style: 'subtitle' } : {},
		{
			table: { widths: ['*', '*', '*', '*'], body: [attrCells] },
			layout: 'noBorders',
			margin: [0, 10, 0, 0]
		}
	];

	if (view.appearance) {
		content.push(band('Appearance'), { text: view.appearance, style: 'body' });
	}
	if (view.quest) {
		content.push(band('Quest'), { text: view.quest, style: 'body' });
	}
	if (view.motifs.length) {
		content.push(band('Motifs'), { text: view.motifs.join('   ·   '), style: 'body' });
	}
	if (view.talents.length) {
		content.push(band('Talents'), {
			ul: view.talents.map((t) => `${t.name} (${t.state})`),
			style: 'body'
		});
	}
	if (view.equipment.length) {
		content.push(band('Gear'), {
			ul: view.equipment.map((e) => `${e.name} — ${e.tier}`),
			style: 'body'
		});
	}
	if (view.bonds.length) {
		content.push(band('Bonds'), {
			ul: view.bonds.map((b) => `${b.targetName}: ${b.text}`),
			style: 'body'
		});
	}

	const footerBits = [
		`Resolve ${view.resolve.current}/${view.resolve.max}`,
		view.languages.length ? `Languages: ${view.languages.join(', ')}` : '',
		view.conditions.length ? `Conditions: ${view.conditions.join(', ')}` : ''
	].filter(Boolean);
	content.push(band('Status'), { text: footerBits.join('     '), style: 'body' });

	if (view.notes) {
		content.push(band('Notes'), { text: view.notes, style: 'body' });
	}

	content.push({ text: DISCLAIMER, style: 'disclaimer', margin: [0, 20, 0, 0] });

	return {
		pageSize: 'LETTER',
		pageMargins: [40, 40, 40, 40] as [number, number, number, number],
		defaultStyle: { fontSize: 10, color: INK },
		styles: {
			title: { fontSize: 26, bold: true, color: INK },
			subtitle: { fontSize: 12, color: SOFT, margin: [0, 2, 0, 0] },
			band: { fontSize: 10, bold: true, color: BAND_TEXT, fillColor: ACCENT, margin: [6, 3, 6, 3] },
			attrValue: { fontSize: 22, bold: true, color: INK },
			attrName: { fontSize: 9, color: SOFT },
			body: { fontSize: 10, color: INK, margin: [0, 2, 0, 0] },
			disclaimer: { fontSize: 7, color: SOFT, italics: true }
		},
		content
	};
}

async function getPdfMake() {
	const pdfMake = (await import('pdfmake/build/pdfmake')).default;
	const pdfFonts = (await import('pdfmake/build/vfs_fonts')).default;
	pdfMake.addVirtualFileSystem(pdfFonts);
	return pdfMake;
}

/** Render the sheet and return the PDF bytes. Browser-only. */
export async function generatePDF(view: CharacterView): Promise<Uint8Array> {
	const docDefinition = buildDocDefinition(view);
	const pdfMake = await getPdfMake();
	return await pdfMake.createPdf(docDefinition).getBuffer();
}

/** Trigger a browser download of the sheet PDF. */
export async function downloadPDF(view: CharacterView): Promise<void> {
	const pdfMake = await getPdfMake();
	const filename = `${(view.name || 'adventurer').replace(/[^a-z0-9]+/gi, '-').toLowerCase()}.pdf`;
	await pdfMake.createPdf(buildDocDefinition(view)).download(filename);
}
