import { describe, expect, it } from 'vitest';
import { getTarotProcedures, getBestiary, getRules } from '$lib/server/content/loader';

/**
 * The tarot procedure catalog: every in-session tarot procedure the campaign
 * feature runs, plus the verbatim oracle lookup tables those procedures resolve
 * against. Generated by scripts/content-import/md-procedures.mjs — never
 * hand-authored.
 */
describe('tarot procedure catalog', () => {
	it('loads a unique, versioned catalog', () => {
		const file = getTarotProcedures();
		expect(file.schemaVersion).toBe(1);
		expect(file.procedures.length).toBeGreaterThan(0);
		expect(new Set(file.procedures.map((p) => p.id)).size).toBe(file.procedures.length);
		expect(file.procedures.every((p) => p.steps.length > 0)).toBe(true);
	});

	it('contains only supported-v1 runtime entries with unique step ids', () => {
		for (const procedure of getTarotProcedures().procedures) {
			expect(procedure.scope).toBe('supported-v1');
			expect(new Set(procedure.steps.map((s) => s.id)).size).toBe(procedure.steps.length);
		}
	});

	it('does not replace the manual 50 percent choice with a draw', () => {
		const manual = getTarotProcedures()
			.procedures.flatMap((procedure) => procedure.steps)
			.find((step) => step.id === 'flat-fifty-percent-choice');
		expect(manual?.operation).toBe('manual-choice');
	});
});

describe('tarot procedure references', () => {
	it('resolves every lookupTableId', () => {
		const file = getTarotProcedures();
		const tableIds = new Set(file.lookupTables.map((t) => t.id));
		for (const procedure of file.procedures) {
			for (const step of procedure.steps) {
				if (step.lookupTableId) {
					expect(tableIds.has(step.lookupTableId), `${procedure.id}/${step.id}`).toBe(true);
				}
			}
		}
	});

	it('resolves every ruleEntryId against the committed rules reference', () => {
		const known = new Set(getRules().map((r) => r.id));
		for (const procedure of getTarotProcedures().procedures) {
			for (const id of procedure.ruleEntryIds) {
				expect(known.has(id), `${procedure.id} cites ${id}`).toBe(true);
			}
		}
	});

	it('resolves every modifierId', () => {
		const file = getTarotProcedures();
		const modifierIds = new Set(file.modifiers.map((m) => m.id));
		for (const procedure of file.procedures) {
			for (const id of procedure.modifierIds) {
				expect(modifierIds.has(id), `${procedure.id} cites modifier ${id}`).toBe(true);
			}
		}
	});

	it('defines Guard as an any-suit shield-gated Initiative replacement', () => {
		const file = getTarotProcedures();
		const procedure = file.procedures.find((p) => p.id === 'challenge-guard');
		const modifier = file.modifiers.find((m) => m.id === 'challenge-guard');

		expect(procedure?.ruleEntryIds).toContain('challenge-guard');
		expect(procedure?.modifierIds).toContain('challenge-guard');
		expect(procedure?.steps.map((step) => step.id)).toEqual([
			'replace-initiative',
			'discard-old-initiative'
		]);
		expect(modifier).toMatchObject({
			behaviorId: 'replace-initiative',
			params: {
				requiresShield: true,
				anySuit: true,
				discardsOldInitiative: true
			}
		});
	});

	it('resolves every draw formulaId', () => {
		const file = getTarotProcedures();
		const formulaIds = new Set(file.formulas.map((f) => f.id));
		for (const procedure of file.procedures) {
			for (const step of procedure.steps) {
				if (step.draw?.kind === 'formula') {
					expect(formulaIds.has(step.draw.formulaId), `${procedure.id}/${step.id}`).toBe(true);
				}
			}
		}
	});
});

/** Ordered key lists per deck; a row's range is inclusive of both ends. */
const MINOR_KEYS = [
	'I',
	'II',
	'III',
	'IV',
	'V',
	'VI',
	'VII',
	'VIII',
	'IX',
	'X',
	'Page',
	'Knight',
	'Queen',
	'King'
];
const MAJOR_KEYS = [
	'I',
	'II',
	'III',
	'IV',
	'V',
	'VI',
	'VII',
	'VIII',
	'IX',
	'X',
	'XI',
	'XII',
	'XIII',
	'XIV',
	'XV',
	'XVI',
	'XVII',
	'XVIII',
	'XIX',
	'XX',
	'XXI'
];

function expandRange(deck: 'major' | 'minor', from: string, to: string): string[] {
	const keys = deck === 'major' ? MAJOR_KEYS : MINOR_KEYS;
	const start = keys.indexOf(from);
	const end = keys.indexOf(to);
	expect(start, `unknown ${deck} key ${from}`).toBeGreaterThanOrEqual(0);
	expect(end, `unknown ${deck} key ${to}`).toBeGreaterThanOrEqual(0);
	expect(end, `inverted range ${from}–${to}`).toBeGreaterThanOrEqual(start);
	return keys.slice(start, end + 1);
}

describe('oracle lookup tables', () => {
	it('covers every card of its deck exactly once, with no gaps or overlaps', () => {
		for (const table of getTarotProcedures().lookupTables) {
			if (table.axis === 'suit-by-step') continue; // keyed by suit, not card
			const hits = new Map<string, number>();
			for (const row of table.rows) {
				if (row.key.kind !== 'card-range') continue;
				for (const key of expandRange(table.deck, row.key.from, row.key.to)) {
					hits.set(key, (hits.get(key) ?? 0) + 1);
				}
			}
			const expected = table.deck === 'major' ? MAJOR_KEYS.length : MINOR_KEYS.length;
			expect(hits.size, `${table.id} key count`).toBe(expected);
			for (const [key, count] of hits) {
				expect(count, `${table.id} key ${key} claimed ${count}x`).toBe(1);
			}
		}
	});

	it('gives every row a cell for every column', () => {
		for (const table of getTarotProcedures().lookupTables) {
			for (const row of table.rows) {
				expect(row.cells.length, `${table.id} row`).toBe(table.columns.length);
				for (const cell of row.cells) {
					expect(cell.text.trim().length, `${table.id} empty cell`).toBeGreaterThan(0);
				}
			}
		}
	});

	it('resolves every denizen cross-reference to a real entry', () => {
		const denizenIds = new Set(getBestiary().map((d) => d.id));
		for (const table of getTarotProcedures().lookupTables) {
			for (const row of table.rows) {
				for (const cell of row.cells) {
					for (const ref of cell.references) {
						if (ref.collection !== 'denizens') continue;
						expect(denizenIds.has(ref.entryId), `${table.id} cites denizen ${ref.entryId}`).toBe(
							true
						);
					}
				}
			}
		}
	});

	/**
	 * Every bracket in a convention-declaring table must be typed. The earlier
	 * version of this test matched cell text against the same narrow enum the
	 * parser used, so it asserted the implementation back at itself and could
	 * never catch [Swords] or [1–2] going untyped — which is exactly what had
	 * happened.
	 */
	it('types every bracket in a table declaring the discard-top convention', () => {
		const declaring = getTarotProcedures().lookupTables.filter(
			(t) => t.bracketConvention === 'minor-discard-top'
		);
		expect(declaring.length).toBeGreaterThan(0);
		for (const table of declaring) {
			for (const row of table.rows) {
				for (const cell of row.cells) {
					const brackets = cell.text.match(/\[[^\]]{1,14}\]/g) ?? [];
					expect(brackets.length, `${table.id} "${cell.text.slice(0, 40)}"`).toBe(
						cell.tokens.length
					);
				}
			}
		}
	});

	it('does not invent tokens in tables without the convention', () => {
		for (const table of getTarotProcedures().lookupTables) {
			if (table.bracketConvention) continue;
			for (const row of table.rows) {
				for (const cell of row.cells) {
					expect(cell.tokens, `${table.id} should have no tokens`).toEqual([]);
				}
			}
		}
	});

	/** Codex review: the <br> strip welded clauses together without a space. */
	it('never welds two clauses together where the source had a line break', () => {
		for (const table of getTarotProcedures().lookupTables) {
			for (const row of table.rows) {
				for (const cell of row.cells) {
					expect(cell.text, `${table.id} welded clause`).not.toMatch(/\S•/);
				}
			}
		}
	});
});
